version: "3"
services:
  input:
    image: nginx:1.16.0-alpine
    container_name: sapporo-fileserver-input
    restart: always
    working_dir: /opt/SAPPORO/SAPPORO-fileserver
    volumes:
      - ${PWD}/log/nginx:/var/log/nginx
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/run:/var/run/nginx
      - ${PWD}/nginx/cache:/var/cache/nginx
      - ${PWD}/input_data:/opt/SAPPORO/SAPPORO-fileserver/input_data
    user: ${UID:-0}:${GID:-0}
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 1124:1124
    networks:
      - sapporo
  # output:
  #   image: minio/minio:RELEASE.2019-07-17T22-54-12Z
  #   container_name: sapporo-fileserver-output
  #   restart: always
  #   volumes:
  #     - ${PWD}/output_data:${PWD}/output_data
  #   working_dir: ${PWD}
  #   environment:
  #     MINIO_ACCESS_KEY: access_key
  #     MINIO_SECRET_KEY: secret_access_key
  #   user: ${UID:-0}:${GID:-0}
  #   command: ["server", "--address", "0.0.0.0:80", "${PWD}/output_data"]
  #   ports:
  #     - 1123:80
  #   networks:
  #     - sapporo

networks:
  sapporo:
    external:
      name: sapporo-network
