version: "3"
services:
  input:
    image: nginx:1.16.0-alpine
    container_name: sapporo-fileserver-input
    restart: always
    volumes:
      - ${PWD}/data/input_data:/data
      - ${PWD}/etc/nginx_cache:/var/cache/nginx
      - ${PWD}/etc/nginx_run:/var/run/nginx
      - ${PWD}/etc/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/log/nginx:/var/log/nginx
    user: ${UID:-0}:${GID:-0}
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 1123:8080
    networks:
      - sapporo
  output:
    image: minio/minio:RELEASE.2019-07-17T22-54-12Z
    container_name: sapporo-fileserver-output
    restart: always
    volumes:
      - ${PWD}/data/output_data:/data
      - ${PWD}/log/minio:/var/log/minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-access_key}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-secret_access_key}
      MINIO_USERNAME: ${UID:-0}
      MINIO_GROUPNAME: ${GID:-0}
      MINIO_HTTP_TRACE: /var/log/minio/access.log
    user: ${UID:-0}:${GID:-0}
    command: ["server", "--address", "0.0.0.0:8080", "/data"]
    ports:
      - 1124:8080
    networks:
      - sapporo

networks:
  sapporo:
    external:
      name: sapporo-network
