version: "3"
services:
  app:
    image: suecharo/sapporo-fileserver:v0.3.4
    container_name: sapporo-fileserver-app
    restart: always
    volumes:
      - ./data:/data
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_access_key
    command: ["server", "--address", "0.0.0.0:1123", "/data"]
    ports:
      - 1123:1123
