version: "3"
services:
  app:
    image: suecharo/sapporo-service:v0.3.6
    container_name: sapporo-service-app
    restart: always
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/lib/docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/etc/uwsgi:/opt/SAPPORO/SAPPORO-service/etc/uwsgi
      - ${PWD}/log:/opt/SAPPORO/SAPPORO-service/log
      - ${PWD}/run:/opt/SAPPORO/SAPPORO-service/run
      - ${PWD}/service-info.yml:/opt/SAPPORO/SAPPORO-service/service-info.yml
      - ${PWD}/workflow-info.yml:/opt/SAPPORO/SAPPORO-service/workflow-info.yml
    environment:
      - DEBUG=False # Flask debug mode
      - LOG_LEVEL=DEBUG # DEBUG or INFO
      - ENABLE_GET_RUNS=False
      - ENABLE_TOKEN_AUTH=False
    user: ${UID:-0}:999 # Docker group
    command: ["uwsgi", "/opt/SAPPORO/SAPPORO-service/etc/uwsgi/uwsgi.ini"]
    networks:
      - sapporo
  web:
    image: nginx:1.16.0-alpine
    container_name: sapporo-service-web
    restart: always
    volumes:
      - ${PWD}/etc/nginx/cache:/var/cache/nginx
      - ${PWD}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/etc/nginx/run:/var/run/nginx
      - ${PWD}/etc/uwsgi:/etc/nginx/uwsgi
      - ${PWD}/log/nginx:/var/log/nginx
    user: ${UID:-0}:${GID:-0}
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - sapporo
    ports:
      - 1122:8080
    depends_on:
      - app

networks:
  sapporo:
    external:
      name: sapporo-network
