version: "3"
services:
  app:
    image: suecharo/sapporo-service:v0.3.5
    container_name: sapporo-service-app
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /var/lib/docker:/var/lib/docker
      - ${PWD}/etc:/opt/SAPPORO/SAPPORO-service/etc
      - ${PWD}/log:/opt/SAPPORO/SAPPORO-service/log
      - ${PWD}/run:/opt/SAPPORO/SAPPORO-service/run
      - ${PWD}/src:/opt/SAPPORO/SAPPORO-service/src
      - ${PWD}/service-info.yml:/opt/SAPPORO/SAPPORO-service/service-info.ym
      - ${PWD}/workflow-info.yml:/opt/SAPPORO/SAPPORO-service/workflow-info.yml
    networks:
      - sapporo
    environment:
      - LOG_LEVEL=INFO # DEBUG or INFO
      - ENABLE_GET_RUNS=False
      - ENABLE_TOKEN_AUTH=False
    command: ["/bin/bash", "/opt/SAPPORO/SAPPORO-service/entry_point.sh"]
  web:
    image: nginx:1.16.0-alpine
    container_name: sapporo-service-web
    depends_on:
      - app
    restart: always
    volumes:
      - ${PWD}/etc:/opt/SAPPORO/SAPPORO-service/etc
      - ${PWD}/log/nginx:/var/log/nginx
    networks:
      - sapporo
    ports:
      - 1122:80

networks:
  sapporo:
    external:
      name: sapporo-network
