version: "3"
services:
  app:
    image: suecharo/sapporo-web:v0.3.5
    container_name: sapporo-web-app
    depends_on:
      - database
    restart: always
    volumes:
      - ./SAPPORO-web:/opt/SAPPORO-web/SAPPORO-web
      - ./config:/opt/SAPPORO-web/config
      - ./log:/opt/SAPPORO-web/log
    networks:
      - sapporo
    environment:
      - LOG_LEVEL=INFO # DEBUG or INFO
      - LANGUAGE_CODE=en
      - TIME_ZONE=Asia/Tokyo
      - ENABLE_USER_SIGNUP=True
      - POSTGRES_USER=sapporo-web-user
      - POSTGRES_PASSWORD=sapporo-web-passwd
      - POSTGRES_DB=sapporo-web
      - POSTGRES_PORT=5432
    command: ["/bin/bash", "/opt/SAPPORO-web/entry_point.sh"]
  web:
    image: nginx:1.16.0-alpine
    container_name: sapporo-web-web
    depends_on:
      - app
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config:/opt/SAPPORO-web/config
      - ./log:/opt/SAPPORO-web/log
      - ./SAPPORO-web/static:/opt/SAPPORO-web/SAPPORO-web/static
    networks:
      - sapporo
    ports:
      - 1121:80
  database:
    image: postgres:11.2-alpine
    container_name: sapporo-web-database
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sapporo
    environment:
      - POSTGRES_USER=sapporo-web-user
      - POSTGRES_PASSWORD=sapporo-web-passwd
      - POSTGRES_DB=sapporo-web
      - POSTGRES_PORT=5432

volumes:
  postgres-data:

networks:
  sapporo:
    external:
      name: sapporo-network
