workflows:
  - workflow_name: trimming_and_qc
    workflow_version: 0c33f861553629b1e6fb4161686ab47670c9ed97
    workflow_location: https://raw.githubusercontent.com/suecharo/SAPPORO/develop/SAPPORO-service/develop/test_workflow/trimming_and_qc.cwl
    workflow_parameters_template_location: https://raw.githubusercontent.com/suecharo/SAPPORO/develop/SAPPORO-service/develop/test_workflow/trimming_and_qc_run_template.yml
    language_type: CWL
    language_version: v1.0
  - workflow_name: bwa_mapping_pe
    workflow_version: 0c33f861553629b1e6fb4161686ab47670c9ed97
    workflow_location: https://raw.githubusercontent.com/suecharo/SAPPORO/develop/SAPPORO-service/develop/test_workflow/bwa_mapping_pe.cwl
    workflow_parameters_template_location: https://raw.githubusercontent.com/suecharo/SAPPORO/develop/SAPPORO-service/develop/test_workflow/bwa_mapping_pe_run_template.yml
    language_type: CWL
    language_version: v1.0
