swagger: "2.0"
info:
  title: SAPPORO-service REST-API Definition
  description: Specification sheet on SAPPORO-service REST-API
  version: 1.0.0
host: localhost:8002
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /service-info:
    get:
      summary: Get information about Workflow Execution Service.
      description: |-
        May include information related (but not limited to) the workflow descriptor formats, versions supported, the WES API versions supported, and information about general service availability.
      parameters:
        - name: fields
          in: query
          description: Specify fields using comma-separated values.
          required: false
          format: string
      responses:
        200:
          description: Get information about Workflow Execution Service.
          schema:
            type: object
            properties:
              workflow_engines:
                type: object
                properties:
                  name:
                    type: string
                    example: "cwltool"
                  version:
                    type: string
                    example: "1.0.20181201184214"
                  excutable_workflows:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          example: "CWL"
                        version:
                          type: string
                          example: "v1.0.2"
              state_counts:
                type: array
                items:
                  type: object
                  properties:
                    type: object
                    properties:
                    state:
                      type: string
                      example: RUNNING
                    count:
                      type: int
                      example: 0
              supported_wes_versions:
                type: array
                items:
                  type: string
                  example: v1.0.0
              auth_instructions_url:
                type: string
                example: https://dummy_auth_instructions_url/
              contact_info_url:
                type: string
                example: https://dummy_contact_info_url/
      tags:
        - WorkflowExecutionService
  /workflows:
    get:
      summary: Get the registered workflow.
      description: |-
        Get the registered workflow.
      responses:
        200:
          description: Get the registered workflow.
          schema:
            type: object
            properties:
              workflows:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: int
                      example: 0
                    name:
                      type: string
                      example: download-GRCh38
                    engine:
                      type: string
                      example: cwltool
                    version:
                      type: string
                      example: v1.0.2
                    description:
                      type: string
                      example: Workflow for downloading fasta file and bwa index of GRCh38
                    parameters:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: key_1
                          description:
                            type: string
                            example: "description_1"
              next_page_token:
                type: string
                example: "dummy_next_page_token"
      tags:
        - WorkflowExecutionService
